project:
  type: website

website:
  title: "TengFei's Blog"
  navbar:
    right:
      - article.qmd
      - icon: github
        href: https://github.com/fly-t
      - icon: qr-code-scan
        href: https://raw.githubusercontent.com/fly-t/images/main/blog/wechat-2022-11-27-16-30-56.png
      
format:
  html:
    theme: 
      light: flatly
      # theme: https://bootswatch.com/      [ cyborg  minty]
      # theme switch:  https://quarto.org/docs/output-formats/html-themes.html
      dark: [quartz, theme-switch.scss]
    css: styles.css




execute: 
  freeze: auto



